### ISSUE TITLE
ASH: Connected, but no ZigBee frames being sniffed

### ISSUE THREAD

**Issue by kevpfowler** [zsmartsystems/com.zsmartsystems.zigbee.sniffer#12]
Need some help getting this working for me. I have a Nortek HUSBZB-1 stick that I want to use to sniff a ZigBee (HA 1.2) active network I have running. When I run the ZigBeeSniffer.jar, I see what appears to be some message exchange with the HUSBZB-1, but I do not see any ZigBee frames (even encrypted) being dumped to the console. 

```bash
$ java -jar ZigBeeSniffer.jar -port /dev/ttyUSB1 -baud 11520 -flow hardware
Z-Smart Systems Ember Packet Sniffer
NCP initialisation starting...
Opened serial port /dev/ttyUSB1 at 11520
DEBUG  22:40:52.947  Opening port /dev/ttyUSB1 at 11520 baud with FLOWCONTROL_OUT_RTSCTS.
DEBUG  22:40:53.167  AshFrameHandler thread started
DEBUG  22:40:53.174  --> TX ASH frame: AshFrameRst []
DEBUG  22:40:53.276  ASH: TX EZSP queue: 1
DEBUG  22:40:54.777  --> TX ASH frame: AshFrameRst []
DEBUG  22:40:56.158  <-- RX ASH frame: AshFrameRstAck [version=2, resetCode=11, Reset: Software]
DEBUG  22:40:56.158  ASH: Connected
```

Is there something more I need to do? I am assuming /dev/ttyUSB1 is the correct device - the other one created when I connect the stick is /dev/ttyUSB0, but I think that is ZWave? If I try using that device the ASH frames are never responded to.

Appreciate any help suggestions on getting it to sniff ZigBee packets.
Kevin

**Comment by cdjackson** [comment]
There should be more printed than just this - the system is not initialised still (based on this log above). Are you compiling the sniffer yourself? I would suggest to use version ```1.3.0``` of the libraries if you are compiling yourself (I should update the pom to change this).

**Comment by kevpfowler** [comment]
I was using the jar binary downloaded from the README, my java/maven know-how being limited. I just updated the pom.xml to point to 1.3.0 version of your supporting libraries, and ran 'mvn package'. This created a rather small jar file in target/:

```bash
$ ls -l target
total 40
drwxr-xr-x 3 kfowler kfowler  4096 Jan 21 08:27 classes
-rw-r--r-- 1 kfowler kfowler 22911 Jan 21 08:27 com.zsmartsystems.zigbee.sniffer-1.0.0-SNAPSHOT.jar
drwxr-xr-x 3 kfowler kfowler  4096 Jan 21 08:27 generated-sources
drwxr-xr-x 2 kfowler kfowler  4096 Jan 21 08:27 maven-archiver
drwxr-xr-x 3 kfowler kfowler  4096 Jan 21 08:27 maven-status
```
so I assume I am not building it right. What is the correct procedure for building this?

**Comment by cdjackson** [comment]
To be honest I don't tend to use maven to compile this - I normally end up doing it in the Eclipse IDE. I will try and take a look at this later to see if maven works for me and if not I'll try and resolve it.

**Comment by kevpfowler** [comment]
Thank you, that would be appreciated - I have not used Eclipse in a long while. Or if you update the ZigBeeSniffer.jar binary linked to from the README, I could see if that works with this stick. Not sure what is easier for you in the short/long run.

**Comment by cdjackson** [comment]
I've updated the pom so that it now includes the dependencies, so hopefully this will work now. I dont have a dongle here to test, but the JAR runs and complains about the serial port so it should work.

**Comment by kevpfowler** [comment]
Awesome. I can build with 'mvn package' successfully, and running with that jar (on my correct channel) I am getting packets! There is one "Failed to load class" error/warning on startup, but otherwise appears to be working properly.

```bash
com.zsmartsystems.zigbee.sniffer/target$ java -jar com.zsmartsystems.zigbee.sniffer-1.0.0-SNAPSHOT.jar -port /dev/ttyUSB1 -baud 57600 -channel 15 -flow hardware
Z-Smart Systems Ember Packet Sniffer
NCP initialisation starting...
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Opened serial port /dev/ttyUSB1 at 57600
Ember NCP version     : 5.4.1.0
Ember NCP EUI         : 000D6F0011F5DE10
NCP initialisation complete...
Wireshark destination : /127.0.0.1:17754
Logging on channel    : 15
WiresharkZepFrame [sequence=00000000, lqi=255, data={41 88 EB 01 11 FF FF 00 00 09 12 FC FF 00 00 01 09 D3 E8 80 FE FF 57 0B 00 28 62 61 02 00 D3 E8 80 FE FF 57 0B 00 00 EF FF EA D4 A9 4C 4A 4E 2B AB 56}]
WiresharkZepFrame [sequence=00000001, lqi=255, data={41 88 BC 01 11 FF FF D8 01 09 12 FC FF D8 01 01 AA 12 38 DD FE FF 6F 0D 00 28 52 4B 02 00 12 38 DD FE FF 6F 0D 00 00 21 AF F6 D0 11 0E 22 EE 91 C9 3A}]
WiresharkZepFrame [sequence=00000002, lqi=255, data={41 88 EC 01 11 FF FF 00 00 09 12 FC FF 00 00 01 0A D3 E8 80 FE FF 57 0B 00 28 63 61 02 00 D3 E8 80 FE FF 57 0B 00 00 96 62 1C 98 66 C6 D4 6C C5 8C 8F}]
WiresharkZepFrame [sequence=00000003, lqi=255, data={41 88 BD 01 11 FF FF D8 01 09 12 FC FF D8 01 1E AB 12 38 DD FE FF 6F 0D 00 28 53 4B 02 00 12 38 DD FE FF 6F 0D 00 00 A2 40 EA 24 46 5E 3F 4C 66 27 86 30}]
WiresharkZepFrame [sequence=00000004, lqi=255, data={41 88 ED 01 11 FF FF 00 00 09 12 FC FF D8 01 1D AB 12 38 DD FE FF 6F 0D 00 28 64 61 02 00 D3 E8 80 FE FF 57 0B 00 00 4A ED CE 0C 30 69 0C DC 42 37 59 47}]
```

Thank you for the timely attention and fix
