### ISSUE TITLE
Scanning option

### ISSUE THREAD

**Issue by sraillard** [zsmartsystems/com.zsmartsystems.zigbee.sniffer#15]
When working with mutiple PAN and coordinators, it could be interessing to have a global view of what is happening on the 16 channels. As beacons are sent by each coordinators at regular intervals, having a scanning option will help to see what is happening on all the channels.

I was thinking of a command line option like "ScanningInterval" (in seconds) that will change the channel of the module every x seconds. 

Can we call the function "emberMfg.doMfglibSetChannel(ZigBeeChannel.create(channelId))" more than one time to change dynamically the listening channel?

**Comment by cdjackson** [comment]
I think it should be fine to change the channel. IMHO this is not a useful option - at least for most people - since you will obviously loose traffic. Most people will be trying to look at what's happening on a network rather than a more global scan, but if you have a use case for this then I'm happy to add it to the sniffer.

**Comment by sraillard** [comment]
For me, this was for surveying (and not to get everything from all the channels, this is impossible). The idea is when at the office or when going onsite to check some installation, it could be nice to have an overview of what could happen on the different channels. With a scanning interval of 5 seconds, there is enough time to get a beacon from a coordinator and then we easily and quickly see all the active PAN's and on which channels there are.

**Comment by cdjackson** [comment]
That's fine - I'm happy to accept a PR for this if you like...

**Comment by sraillard** [comment]
Ok, I'll see with @mikomarrache if he can prepare a PR for that.

**Comment by mikomarrache** [comment]
I just created a PR for that, #17

**Comment by cdjackson** [comment]
Closed by #17
