### ISSUE TITLE
Compatibility with ITead Zigbee 3.0 USB Dongle (Model: 9888010100045)?

### ISSUE THREAD

**Issue by Hedda** [zsmartsystems/com.zsmartsystems.zigbee.sniffer#25]
@cdjackson Wondering if this new dongle ships with a Zigbee firmware that is compatible out-of-the-box with this sniffer project?

https://www.cnx-software.com/2021/03/18/itead-zigbee-3-0-usb-dongle-features-silicon-labs-efr32mg21-mcu/

https://www.itead.cc/zigbee-3-0-usb-dongle.html

**Comment by cdjackson** [comment]
Yes it should be fine.

**Comment by Hedda** [comment]
Thanks!
