### ISSUE TITLE
Request for recompiled JAR file

### ISSUE THREAD

**Issue by carlsondev** [zsmartsystems/com.zsmartsystems.zigbee.sniffer#29]
I recently found this project which looks extremely useful; however, I can't connect to my device because the protocol version is version 9. 

This is simply because of a check in the [com.zsmartsystems.zigbee.dongle.ember](https://github.com/zsmartsystems/com.zsmartsystems.zigbee/tree/master/com.zsmartsystems.zigbee.dongle.ember) dependency where the `EZSP_MAX_VERSION=8` in the compiled version of this program. That variable was recently updated to `10`, so, to help myself and others, I was hoping that an updated JAR file could be compiled and uploaded, possibly under "Releases" or "Tags", to help with future debugging. 

Thank you to the single person who appears to be maintaining most of the code in this organization. Great work!

**Comment by MattWestb** [comment]
The latest EZSP protocol released is 11 and very likely next release is getting 12 then many changes is made with functions and commands.

**Comment by nonodename** [comment]
+1 for updating the compiled jar, but to update to latest JSSC which supports ARM Macs. The 2.8.0 version throws an InvocationTargetException: Caused by: java.lang.UnsatisfiedLinkError: jssc.SerialNativeInterface.openPort(Ljava/lang/String;Z)J

**Comment by Electrocat01** [comment]
Hi everyone, I rebuilt the project with the latest version of ZSS ZigBee wich have a newer JSSC version so it don't crash anymore (at least on Windows 11).

You can find it down [this release](https://github.com/Electrocat01/com.zsmartsystems.zigbee.sniffer/releases/tag/v1.0.1-Pryam) (I can't upload JARs here sorry).

I hope it helps and please let me know if it works or not!

**Comment by cdjackson** [comment]
The JAR can be found in the releases section.
